/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    CtaButton: typeof import('./src/components/CtaButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    MenuBtn: typeof import('./src/components/MenuBtn.vue')['default']
    MenuPanel: typeof import('./src/components/MenuPanel.vue')['default']
    MusicCard: typeof import('./src/components/MusicCard.vue')['default']
    PageCard: typeof import('./src/components/PageCard.vue')['default']
    PersonCard: typeof import('./src/components/PersonCard.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ThreeBallLoading: typeof import('./src/components/Loading/ThreeBallLoading.vue')['default']
    TypewriterText: typeof import('./src/components/TypewriterText.vue')['default']
    WallpaperSwiper: typeof import('./src/components/WallpaperSwiper.vue')['default']
  }
}
