/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElIco: typeof import('element-plus/es')['ElIco']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpNo: typeof import('~icons/ep/no')['default']
    IEpNotebook: typeof import('~icons/ep/notebook')['default']
    MenuBtn: typeof import('./src/components/MenuBtn.vue')['default']
    MenuPanel: typeof import('./src/components/MenuPanel.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ThreeBallLoading: typeof import('./src/components/Loading/ThreeBallLoading.vue')['default']
  }
}
